language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
before_install:
  - yes | sdkmanager "platforms;android-27"
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - ./gradlew html:dist
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./html/build/dist
  on:
    branch: master